name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER:  ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "finalizando el login"
    - name: Build Docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t bkackhan/docker-graphql:$NEW_VERSION .
        docker build -t bkackhan/docker-graphql:latest .
    - name: Push docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push bkackhan/docker-graphql:$NEW_VERSION
        docker push bkackhan/docker-graphql:latest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
